# Generated by Django 4.2.24 on 2025-10-22 15:11

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'auth_user',
                'ordering': ['-date_joined'],
                'swappable': 'AUTH_USER_MODEL',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('protocol', models.CharField(db_index=True, help_text='Protocolo único da O.S.', max_length=100, unique=True)),
                ('so_number', models.CharField(db_index=True, max_length=100, verbose_name='Número da O.S.')),
                ('type', models.CharField(choices=[('administrative', 'Administrativa'), ('installation', 'Instalação'), ('preventive_maintenance', 'Manutenção Preventiva'), ('corrective_maintenance', 'Manutenção Corretiva'), ('predictive_maintenance', 'Manutenção Preditiva'), ('inspection', 'Vistoria'), ('technical_assistance', 'Assistência Técnica'), ('work_safety', 'Segurança do Trabalho'), ('budget', 'Orçamento'), ('events', 'Eventos')], default='corrective_maintenance', max_length=50, verbose_name='Tipo de Serviço')),
                ('status', models.CharField(choices=[('open', 'Aberta'), ('in_progress', 'Em andamento'), ('completed', 'Concluída'), ('cancelled', 'Cancelada')], default='open', max_length=50, verbose_name='Status')),
                ('provider', models.CharField(choices=[('technical', 'Técnico'), ('specialized', 'Especializado'), ('consulting', 'Consultivo'), ('administrative_provider', 'Administrativo'), ('logistics', 'Logístico'), ('operational', 'Operacional'), ('technological', 'Tecnológico'), ('commercial', 'Comercial'), ('maintenance_provider', 'Manutenção'), ('security', 'Segurança'), ('educational', 'Educacional'), ('communication', 'Comunicação'), ('other', 'Outros Serviços')], default='technical', max_length=50, verbose_name='Prestador')),
                ('priority', models.CharField(choices=[('critical', 'Crítica'), ('high', 'Alta'), ('medium', 'Média'), ('low', 'Baixa')], default='medium', max_length=50, verbose_name='Prioridade')),
                ('recipient_name', models.CharField(max_length=255, verbose_name='Nome do Recebedor/Cliente')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_orders', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Ordem de Serviço',
                'verbose_name_plural': 'Ordens de Serviço',
                'ordering': ['-created_at'],
            },
        ),
    ]
