# Generated by Django 5.2.7 on 2025-12-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'Este nome de usuário já está em uso.'}, max_length=30, unique=True),
        ),
    ]
